# Generated by Django 4.2.5 on 2023-10-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Craftapp', '0005_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
